tasks:
  - init: npm install && npm run dev
    command: npm run dev

ports:
  - name: Web App
    port: 3000
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - GitHub.vscode-pull-request-github
