
tasks:
  - init: npm install && npm run build
    command: npm run dev

ports:
  - name: Web App
    port: 3000
    visibility: public
    onOpen: open-browser


vscode:
  extensions:
    - GitHub.vscode-pull-request-githubare the goodness with others.